### ISSUE TITLE
MSCOCO pretrained model

### ISSUE THREAD

**Issue by murdockhou** [Guillem96/efficientdet-tf#11]
Hi, thanks for your nicely work. I find only VOC pretrained model, is there a plan to upload COCO pretrained model?

**Comment by Guillem96** [comment]
Yes, it is. But first I am grtting the model ready so I can distribuite the training over multiple gpus or tpus

**Comment by murdockhou** [comment]
Thanks, waiting for your work.

**Comment by Guillem96** [comment]
Thanks for being interested in my project 😃
