### ISSUE TITLE
Bad prediction labels in the example notebook

### ISSUE THREAD

**Issue by bessszilard** [Guillem96/efficientdet-tf#12]
First of all, thanks for this library!

I ran the notebook which you [provided](https://github.com/Guillem96/efficientdet-tf/blob/master/examples/EfficientDet_TF_Example.ipynb), and on the algorithm finds "boat" and not "cat". 
My notebook is here:
https://colab.research.google.com/drive/1-tmY7YxhCkvEvPXVExiMCmOyL4JZPTRf

I tried on another image, and instead of writing cars, it writes
![image](https://user-images.githubusercontent.com/48211034/80397975-423e6700-88b7-11ea-8627-89273dfbc17e.png)

What causes the problem?

**Comment by Guillem96** [comment]
Try it now, there was a commit that shouldn't be there. Be sure that you factory reset the colab runtime :)

**Comment by bessszilard** [comment]
Yes, fixed. Thanks.
