### ISSUE TITLE
Will TFLite export be supported?

### ISSUE THREAD

**Issue by lessw2020** [Guillem96/efficientdet-tf#15]
I wasn't able to save a model to test as there was an error with the bounding box code (shown below) but my main question was to find out if TFLite export and quantization will be supported for this project? (need to run on mobile). 

Thanks very much.  
Related - but here is the error when I tried to save the model after running the example notebook:
`--
TypeError                                 Traceback (most recent call last)
<ipython-input-13-3869f28fca84> in <module>()
----> 1 model.save('tester',include_optimizer=False)

26 frames
/usr/local/lib/python3.6/dist-packages/efficientdet/utils/bndbox.py in nms(boxes, class_scores, score_threshold)
    182     all_scores = []
    183 
--> 184     for batch_idx in range(batch_size):
    185         body_fn = partial(body, batch_idx=batch_idx)
    186         # For each class, get the effective boxes, labels and scores

TypeError: 'Tensor' object cannot be interpreted as an integer`

**Comment by Guillem96** [comment]
Save the weights only.

Also, the export to saved-model is incoming.

**Comment by veb-101** [comment]
Any updates on saved_model export?
