### ISSUE TITLE
module 'efficientdet.utils.bndbox' has no attribute 'to_tf_format'

### ISSUE THREAD

**Issue by satulovsky** [Guillem96/efficientdet-tf#17]
First of all, thank you for your clear explanations and clean repo.

When I try running the training example I get the following error:

```
AttributeError: in user code:

    /home/javier/DS_FFC/research/EfficientDet/EfficientDet1/efficientdet/data/voc.py:87 _permute_boxes  *
        bboxes = bb_utils.to_tf_format(bboxes)

    AttributeError: module 'efficientdet.utils.bndbox' has no attribute 'to_tf_format'
```

I looked at the ndbox.py and it does not seem to have it.

**Comment by Guillem96** [comment]
Thanks for opening the issue. I have a merge pending from development branch which fixes this. 😃

**Comment by satulovsky** [comment]
Thank you very much!

**Comment by Guillem96** [comment]
It should work now
