### ISSUE TITLE
Saving/Loading with utils.checkpoint

### ISSUE THREAD

**Issue by JamesDConley** [Guillem96/efficientdet-tf#19]
the utils.checkpoint.save saves in .tf format while utils.checkpoint.load expects .h5 format. Is there another way to save/load a model?

**Comment by Guillem96** [comment]
I am currently working with checkpointing, but I ve been a bit busy this days. In the following days, I'll try to implement a consistent checkpoint API

**Comment by JamesDConley** [comment]
Thank you!
