### ISSUE TITLE
ValueError: Anonymous credentials cannot be refreshed. when downloading pretrained weights

### ISSUE THREAD

**Issue by agnaranjo** [Guillem96/efficientdet-tf#23]
When executing https://github.com/Guillem96/efficientdet-tf/blob/master/examples/EfficientDet_TF_Example.ipynb, in the line:

`model = EfficientDet.from_pretrained('D0-VOC', score_threshold=.3)
`

The following error rises:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-a85221d967d5> in <module>()
----> 1 model = EfficientDet.from_pretrained('D0-VOC', score_threshold=.3)
      2 image_size = model.config.input_size

11 frames
/usr/local/lib/python3.6/dist-packages/google/auth/credentials.py in refresh(self, request)
    146         """Raises :class:`ValueError``, anonymous credentials cannot be
    147         refreshed."""
--> 148         raise ValueError("Anonymous credentials cannot be refreshed.")
    149 
    150     def apply(self, headers, token=None):

ValueError: Anonymous credentials cannot be refreshed.`

Maybe this is related: 

https://stackoverflow.com/questions/51078146/how-to-properly-use-create-anonymous-client-function-in-google-cloud-storage-p

**Comment by Guillem96** [comment]
For now, the google bucket used for this is deleted. I cannot maintain it. Maybe I'll change the storage to a simple Google Drive public directory

**Comment by JamesDConley** [comment]
Did these weights ever end up anywhere? I'm hoping to use this library again- just about the only usable one I've found for efficientdet in tensorflow (at least in terms of being able to retrain).

**Comment by max-mapper** [comment]
I'm experiencing the same issue
