### ISSUE TITLE
Question regarding huber loss

### ISSUE THREAD

**Issue by UmarSpa** [Guillem96/efficientdet-tf#24]
Why the huber loss is mulitplied by 50 ?

>>        return 50. * tf.divide(self.loss_fn(y_true, y_pred), normalizer)

**Comment by UmarSpa** [comment]
And also the normalizer is first multiplied by 4. How come ?

>>        normalizer = tf.multiply(normalizer, tf.constant(4., dtype=tf.float32))

**Comment by Guillem96** [comment]
These values should not be here, I was doing some testing and unfortunately, I upload them. Thanks for the comment
