### ISSUE TITLE
mAP?

### ISSUE THREAD

**Issue by CraigWang1** [Guillem96/efficientdet-tf#3]
Hi, thank you very much for your hard work in your implementation.

Have you trained any models? If so, what were there mAP scores? (VOC, COCO)

**Comment by Guillem96** [comment]
Last month I bought a good GPU, and I am planning to train a model. When I got the results I ll publish the results.

Thanks for getting interested.

**Comment by sampathkethineedi** [comment]
Hi @Guillem96 any update on this?
